const numberButtons = document.querySelectorAll('.digit')
const operationButtons = document.querySelectorAll('.operator')
const equalsButton = document.querySelector('.equals')
const changeSignButton = document.querySelector('.change-sign')
const clearElementButton = document.querySelector('.remove-one-symbol')
const allClearButton = document.querySelector('.all-clear')
const previousOperandTextElement = document.querySelector('.previous-operand')
const currentOperandTextElement = document.querySelector('.current-operand')

const calculator = new Calculator(previousOperandTextElement, currentOperandTextElement)

const appendNumber = () => calculator.appendNumber(button.innerText)
const chooseOperation = () => calculator.chooseOperation(button.innerText)
const compute = () => calculator.compute()
const changeSign = () => calculator.changeSign()
const allClear = () => calculator.clear()
const clearElement = () => calculator.truncateNumber()

numberButtons.forEach(button => button.addEventListener('click', appendNumber))
operationButtons.forEach(button => button.addEventListener('click', chooseOperation))
equalsButton.addEventListener('click', compute)
changeSignButton.addEventListener('click', changeSign)
allClearButton.addEventListener('click', allClear)
clearElementButton.addEventListener('click', clearElement)